[alacritty]
name = "alacritty"
path = "~/.config/alacritty"
git_path = "https://github.com/Adamekka/alacritty.git"

[dwm]
name = "dwm"
path = "~/.config/dwm"
git_path = "https://github.com/Adamekka/dwm.git"

[fish]
name = "fish"
path = "~/.config/fish"
git_path = "https://github.com/Adamekka/fish.git"

[hypr]
name = "hypr"
path = "~/.config/hypr"
git_path = "https://github.com/Adamekka/hypr.git"

[mako]
name = "mako"
path = "~/.config/mako"
git_path = "https://github.com/Adamekka/mako.git"

[mpv]
name = "mpv"
path = "~/.config/mpv"
git_path = "https://github.com/Adamekka/mpv.git"

[picom]
name = "picom"
path = "~/.config/picom"
git_path = "https://github.com/Adamekka/picom.git"

[rofi]
name = "rofi"
path = "~/.config/rofi"
git_path = "https://github.com/Adamekka/rofi.git"

[st]
name = "st"
path = "~/.config/st"
git_path = "https://github.com/Adamekka/st.git"

[waybar]
name = "waybar"
path = "~/.config/waybar"
git_path = "https://github.com/Adamekka/waybar.git"

[xmobar]
name = "xmobar"
path = "~/.config/xmobar"
git_path = "https://github.com/Adamekka/xmobar.git"

[xmonad]
name = "xmonad"
path = "~/.config/xmonad"
git_path = "https://github.com/Adamekka/xmonad.git"
